### ISSUE TITLE
SQLite upgrade to 3.8.xx

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/role_sqlite#1]
Rails, Django need at latest SQLite 3.8.xx, but there only SQLite version 3.7.17 at CentOS7.x

**Comment by qiaofeng1227** [comment]
apt installation has priority over Make installation

**Comment by qiaofeng1227** [comment]
3.35.5 | 3.30.1 | 3.9.2
https://www.sqlite.org/chronology.html

**Comment by zengxc-1996** [comment]
There is only one version  available on ubuntu 20.04:

![image](https://user-images.githubusercontent.com/63622990/121483216-854a9380-ca00-11eb-8f37-093a3bc6535b.png)
